use_frameworks!

target 'CardMagusKit_Example' do
  pod 'CardMagusKit', :path => '../'

  target 'CardMagusKit_Tests' do
    inherit! :search_paths

    pod 'Sync'#, '~> 2'
  	pod 'DATASource'#, '~> 5.8'
	pod 'DATAStack', '~> 6'
	pod 'Networking'
  
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "CardMagusKit"
            target.build_configurations.each do |config|
                config.build_settings['FRAMEWORK_SEARCH_PATHS'] = '${PODS_ROOT}/**'
            end
        end
    end
end